### ISSUE TITLE
TODO:Next stage tasks

### ISSUE THREAD

**Issue by RSS1102** [ErKeLost/wallhaven-desktop#6]
- [ ] auto update.
- [ ] star.
- [ ] Home page Waterfall Flow.
- [ ] Optimize loading progress bar.
- [ ] The system tray has complete functions.
- [ ] Self starting.
- [ ] Star Collection.
- [ ] App icon.
- [ ] typescript.
- [ ] 本地收藏
- [ ] 直接替换windows/mac背景。

---
## Future plans to be determined
- [ ] App Signature

抄送 @ErKeLost
